#!/usr/bin/env python3
"""Build an OVDB-readable SQLite copy of the pinned Chinook database.

DALgo's SQLite adapter addresses records by an `id` column, which the upstream
Chinook tables do not have. This copies the source file, adds a stable text
`id` derived from each table's primary key (every original column is kept) and
can emit the strict OpenVaultDB manifest for the result. The logic mirrors
openvaultdb/cloud/server/prepare_fixture.py, but accepts the demo project's pin
(fixtures/chinook/phase1-acceptance.json) as well as that service's pin; both
files hold identical rows.

usage: prepare_chinook.py SOURCE.sqlite OUTPUT.sqlite [--manifest MANIFEST.yaml]
"""

import hashlib
import shutil
import sqlite3
import sys
from pathlib import Path

ACCEPTED_SHA256 = {
    # datatug/chinook-database ChinookDatabase/DataSources/Chinook_Sqlite.sqlite
    "f82efedb6c5c40734609e168bc5be5616a2eca6b90ed0048451a8674625e03a3",
    # openvaultdb/cloud/server/fixture/Chinook_Sqlite.sqlite
    "7651ba378ac2fcd0dfc3c66fb101f7a7eed3ba39a612ec642b96e20702061f15",
}


def field_type(sql_type: str) -> str:
    kind = sql_type.upper()
    if "INT" in kind:
        return "integer"
    if any(token in kind for token in ("REAL", "FLOA", "DOUB", "DECIMAL", "NUMERIC")):
        return "number"
    return "string"


def main(source: Path, output: Path, manifest_path: Path | None) -> None:
    digest = hashlib.sha256(source.read_bytes()).hexdigest()
    if digest not in ACCEPTED_SHA256:
        raise SystemExit(f"{source}: SHA-256 {digest} is not a pinned Chinook fixture")
    output.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(source, output)
    connection = sqlite3.connect(output)
    manifest = [
        "# Generated by scripts/prepare_chinook.py from the pinned Chinook SQLite file.",
        "database: {id: chinook, schema_mode: strict}",
        f"storage: {{engine: sqlite, path: ../../.demo-data/{output.name}}}",
        "schemas:",
        "  collections:",
    ]
    try:
        tables = [row[0] for row in connection.execute(
            "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name"
        )]
        if len(tables) != 11:
            raise SystemExit(f"expected 11 Chinook tables, got {len(tables)}")
        for table in tables:
            columns = list(connection.execute(f'PRAGMA table_info("{table}")'))
            primary_keys = [name for _, name, _, _, _, pk in sorted(columns, key=lambda c: c[5]) if pk]
            if not primary_keys:
                raise SystemExit(f"table {table} has no primary key")
            row_count = connection.execute(f'SELECT COUNT(*) FROM "{table}"').fetchone()[0]
            connection.execute(f'ALTER TABLE "{table}" ADD COLUMN id TEXT')
            key_expression = " || ',' || ".join(f'CAST("{key}" AS TEXT)' for key in primary_keys)
            connection.execute(f'UPDATE "{table}" SET id = {key_expression}')
            connection.execute(f'CREATE UNIQUE INDEX "ovdb_{table}_id" ON "{table}" (id)')
            if connection.execute(f'SELECT COUNT(*) FROM "{table}"').fetchone()[0] != row_count:
                raise SystemExit(f"row count changed for {table}")
            manifest.extend((f"    {table}:", "      fields:"))
            for _, name, sql_type, _, _, _ in columns:
                manifest.append(f"        {name}: {{type: {field_type(sql_type)}}}")
        connection.commit()
        if connection.execute("PRAGMA integrity_check").fetchone()[0] != "ok":
            raise SystemExit("derived SQLite file failed integrity check")
    finally:
        connection.close()
    if manifest_path is not None:
        manifest_path.write_text("\n".join(manifest) + "\n")


if __name__ == "__main__":
    args = sys.argv[1:]
    manifest = None
    if len(args) == 4 and args[2] == "--manifest":
        manifest = Path(args[3])
        args = args[:2]
    if len(args) != 2:
        raise SystemExit(__doc__)
    main(Path(args[0]), Path(args[1]), manifest)
